export const CATEGORY_GET = "CATEGORY_GET";
export const CATEGORY_ADD_SUCCESS = "CATEGORY_ADD_SUCCESS";
export const CATEGORY_REMOVE_SUCCESS = "CATEGORY_REMOVE_SUCCESS";
export const CATEGORY_EDIT_SUCCESS = "CATEGORY_EDIT_SUCCESS";

export const PRODUCT_GET = "PRODUCT_GET";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_REMOVE_SUCCESS = "PRODUCT_REMOVE_SUCCESS";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";

export const COMMENT_GET = "COMMENT_GET";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_REMOVE_SUCCESS = "COMMENT_REMOVE_SUCCESS";
export const COMMENT_EDIT_SUCCESS = "COMMENT_EDIT_SUCCESS";
